apiVersion: v1
kind: Pod
metadata:
 name: initpod
spec:
 initContainers:
 - name: cont1
   image: busybox
   command: ['sh', '-c', 'echo hello from amit && sleep 10']
 containers:
 - name: main
   image: nginx
   ports:
   - containerPort: 80
